### ISSUE TITLE
运行代码错误

### ISSUE THREAD

**Issue by rain2050** [NJUVISION/PCGCv2#2]
作者您好，谢谢您公开的代码，我在运行您的代码时提示IndexError: pop from empty list错误，您知道如何解决这个问题吗？

**Comment by parkerfan** [comment]
I have the same problem when I run the program again, "IndexError: pop from empty list" will appear, please help me, thank you very much!

The error maybe form here: File "/content/drive/My Drive/PCGCv2/dataprocess/data_loader.py", line 47, in __next__
    return self._perm.pop()
